### ISSUE TITLE
Trouble Accessing CVA6 via SSH

### ISSUE THREAD

**Issue by mrbilandi** [openhwgroup/cva6#2335] opened 2024-07-08 07:57 UTC
Hello,

I have synthesized the CVA6 RTL code for Genesys2 as described in the README file, built the Linux image using the CVA6-SDK, and now I have Linux running on the CVA6 on our board. I set a static IP for eth0, and I can ping the board from a remote machine. However, I can't SSH to it. Whenever I try to SSH to the board, it asks for a password. Since there is no password, I just press enter, but the message 'Permission denied, please try again.' appears. I also tried setting a password like 'root', but the same thing happens: after entering the password(root), it responds with 'Permission denied, please try again.'

Is it supposed to be possible to SSH to the board from a remote machine?

**Comment by mrbilandi** [comment] 2024-07-08 13:06
Just to mention, whenever Linux boots, I don't see the welcoming message "Welcome to Buildroot," and it eventually logs in without any user input. The Linux boot-up process is as follows:

Hello World!
init SPI
status: 0x0000000000000025
status: 0x0000000000000025
SPI initialized!
initializing SD... 
SD command cmd0 	response : 01
SD command cmd55 	response : 01
SD command cmd41 	response : 01
SD command cmd55 	response : 01
SD command cmd41 	response : 00
sd initialized!
gpt partition table header:
	signature:	5452415020494645
	revision:	00010000
	size:		0000005C
	crc_header:	84D98092
	reserved:	00000000
	current lba:	0000000000000001
	backup lda:	0000000001CEA7FF
	partition entries lba:   	0000000000000002
	number partition entries:	00000080
	size partition entries:  	00000080
gpt partition entry 00
	partition type guid:	D5F7127456A1134B81DC867174929325
	partition guid:     	895830B2203A304580EB1BCE0ADF5A73
	first lba:	0000000000000800
	last lba:	0000000000001AFD
	attributes:	0000000000000000
	name:	000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 01
	partition type guid:	AF3DC60F838472478E793D69D8477DE4
	partition guid:     	D3C040C5431AA045A91CC4EB5F1C16A3
	first lba:	0000000000100000
	last lba:	0000000001CEA7DE
	attributes:	0000000000000000
	name:	000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 02
	partition type guid:	00000000000000000000000000000000
	partition guid:     	00000000000000000000000000000000
	first lba:	0000000000000000
	last lba:	0000000000000000
	attributes:	0000000000000000
	name:	000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 03
	partition type guid:	00000000000000000000000000000000
	partition guid:     	00000000000000000000000000000000
	first lba:	0000000000000000
	last lba:	0000000000000000
	attributes:	0000000000000000
	name:	000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
copying boot image .... done!

OpenSBI v0.9
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name             : ARIANE RISC-V
Platform Features         : medeleg
Platform HART Count       : 1
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 1000000Hz
Platform Console Device   : uart8250
Platform HSM Device       : ---
Platform Reboot Device    : ---
Platform Shutdown Device  : ---
Firmware Base             : 0x80000000
Firmware Size             : 220 KB
Runtime SBI Version       : 0.3

Domain0 Name              : root
Domain0 Boot HART         : 0
Domain0 HARTs             : 0*
Domain0 Region00          : 0x0000000002008000-0x000000000200bfff (I)
Domain0 Region01          : 0x0000000002000000-0x0000000002007fff (I)
Domain0 Region02          : 0x0000000080000000-0x000000008003ffff ()
Domain0 Region03          : 0x0000000000000000-0xffffffffffffffff (R,W,X)
Domain0 Next Address      : 0x0000000080200000
Domain0 Next Arg1         : 0x0000000082200000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes

Boot HART ID              : 0
Boot HART Domain          : root
Boot HART ISA             : rv64imafdcbsu
Boot HART Features        : scounteren,mcounteren,mcountinhibit
Boot HART PMP Count       : 16
Boot HART PMP Granularity : 8
Boot HART PMP Address Bits: 54
Boot HART MHPM Count      : 6
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109


U-Boot 2021.07-rc4-g920075ecfa (Jul 08 2024 - 14:25:16 +0200)

CPU:   rv64imafdc
DRAM:  1 GiB
MMC:   xps-spi@20000000:mmc@0: 0
Loading Environment from nowhere... OK
In:    uart@10000000
Out:   uart@10000000
Err:   uart@10000000
Net:   No ethernet found.
Hit any key to stop autoboot:  0 
Device: xps-spi@20000000:mmc@0
Manufacturer ID: 27
OEM: 5048
Name: SD16G 
Bus Speed: 12500000
Mode: MMC legacy
Rd Block Len: 512
SD version 2.0
High Capacity: Yes
Capacity: 14.5 GiB
Bus Width: 1-bit

MMC read: dev # 0, block # 1048576, count 20480 ... 20480 blocks read: OK
## Booting kernel from Legacy Image at 90000000 ...
   Image Name:   CV64A6Linux
   Image Type:   RISC-V Linux Kernel Image (gzip compressed)
   Data Size:    10006808 Bytes = 9.5 MiB
   Load Address: 80200000
   Entry Point:  80200000
   Verifying Checksum ... OK
## Flattened Device Tree blob at bffe08d0
   Booting using the fdt blob at 0xbffe08d0
   Uncompressing Kernel Image
   Using Device Tree in place at 00000000bffe08d0, end 00000000bffe551f

Starting kernel ...

[    0.000000] Linux version 5.10.7 (mojtaba@cassul.eurecom.fr) (riscv64-buildroot-linux-gnu-gcc.br_real (Buildroot 2021.08) 10.3.0, GNU ld (GNU Binutils) 2.36.1) #3 SMP Mon Jul 8 14:27:53 CEST 2024
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] efi: UEFI not found.
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] software IO TLB: mapped [mem 0x00000000bb1e0000-0x00000000bf1e0000] (64MB)
[    0.000000] SBI specification v0.3 detected
[    0.000000] SBI implementation ID=0x1 Version=0x9
[    0.000000] SBI v0.2 TIME extension detected
[    0.000000] SBI v0.2 IPI extension detected
[    0.000000] SBI v0.2 RFENCE extension detected
[    0.000000] SBI v0.2 HSM extension detected
[    0.000000] riscv: ISA extensions acdfim
[    0.000000] riscv: ELF capabilities acdfim
[    0.000000] percpu: Embedded 16 pages/cpu s25048 r8192 d32296 u65536
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 258055
[    0.000000] Kernel command line: earlyprintk
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Sorting __ex_table...
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 945172K/1046528K available (4544K kernel code, 4214K rwdata, 2048K rodata, 184K init, 328K bss, 101356K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU event tracing is enabled.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] riscv-intc: 64 local interrupts mapped
[    0.000000] plic: interrupt-controller@c000000: mapped 30 interrupts with 1 handlers for 2 contexts.
[    0.000000] random: get_random_bytes called from start_kernel+0x2a2/0x410 with crng_init=0
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x5c40939b5, max_idle_ns: 440795202646 ns
[    0.000290] sched_clock: 64 bits at 25MHz, resolution 40ns, wraps every 4398046511100ns
[    0.259485] printk: console [hvc0] enabled
[    0.264723] Calibrating delay loop (skipped), value calculated using timer frequency.. 50.00 BogoMIPS (lpj=250000)
[    0.275366] pid_max: default: 32768 minimum: 301
[    0.285301] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.293524] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.355701] rcu: Hierarchical SRCU implementation.
[    0.368374] EFI services will not be available.
[    0.377056] smp: Bringing up secondary CPUs ...
[    0.381004] smp: Brought up 1 node, 1 CPU
[    0.398147] devtmpfs: initialized
[    0.441134] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.451460] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.470507] NET: Registered protocol family 16
[    0.916155] usbcore: registered new interface driver usbfs
[    0.923901] usbcore: registered new interface driver hub
[    0.930102] usbcore: registered new device driver usb
[    0.963853] clocksource: Switched to clocksource riscv_clocksource
[    1.015821] NET: Registered protocol family 2
[    1.038850] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    1.048465] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    1.059207] TCP bind hash table entries: 8192 (order: 5, 131072 bytes, linear)
[    1.071891] TCP: Hash tables configured (established 8192 bind 8192)
[    1.086040] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.093739] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.105640] NET: Registered protocol family 1
[    1.136744] RPC: Registered named UNIX socket transport module.
[    1.142113] RPC: Registered udp transport module.
[    1.147880] RPC: Registered tcp transport module.
[    1.151934] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   13.632637] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[   13.970240] NFS: Registering the id_resolver key type
[   13.976013] Key type id_resolver registered
[   13.979499] Key type id_legacy registered
[   13.988421] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[   16.276119] io scheduler mq-deadline registered
[   16.280065] io scheduler kyber registered
[   18.214104] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[   18.267900] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[    0.000000] Linux version 5.10.7 (mojtaba@cassul.eurecom.fr) (riscv64-buildroot-linux-gnu-gcc.br_real (Buildroot 2021.08) 10.3.0, GNU ld (GNU Binutils) 2.36.1) #3 SMP Mon Jul 8 14:27:53 CEST 2024
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] efi: UEFI not found.
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] software IO TLB: mapped [mem 0x00000000bb1e0000-0x00000000bf1e0000] (64MB)
[    0.000000] SBI specification v0.3 detected
[    0.000000] SBI implementation ID=0x1 Version=0x9
[    0.000000] SBI v0.2 TIME extension detected
[    0.000000] SBI v0.2 IPI extension detected
[    0.000000] SBI v0.2 RFENCE extension detected
[    0.000000] SBI v0.2 HSM extension detected
[    0.000000] riscv: ISA extensions acdfim
[    0.000000] riscv: ELF capabilities acdfim
[    0.000000] percpu: Embedded 16 pages/cpu s25048 r8192 d32296 u65536
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 258055
[    0.000000] Kernel command line: earlyprintk
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Sorting __ex_table...
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 945172K/1046528K available (4544K kernel code, 4214K rwdata, 2048K rodata, 184K init, 328K bss, 101356K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU event tracing is enabled.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] riscv-intc: 64 local interrupts mapped
[    0.000000] plic: interrupt-controller@c000000: mapped 30 interrupts with 1 handlers for 2 contexts.
[    0.000000] random: get_random_bytes called from start_kernel+0x2a2/0x410 with crng_init=0
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x5c40939b5, max_idle_ns: 440795202646 ns
[    0.000290] sched_clock: 64 bits at 25MHz, resolution 40ns, wraps every 4398046511100ns
[    0.259485] printk: console [hvc0] enabled
[    0.264723] Calibrating delay loop (skipped), value calculated using timer frequency.. 50.00 BogoMIPS (lpj=250000)
[    0.275366] pid_max: default: 32768 minimum: 301
[    0.285301] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.293524] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.355701] rcu: Hierarchical SRCU implementation.
[    0.368374] EFI services will not be available.
[    0.377056] smp: Bringing up secondary CPUs ...
[    0.381004] smp: Brought up 1 node, 1 CPU
[    0.398147] devtmpfs: initialized
[    0.441134] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.451460] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.470507] NET: Registered protocol family 16
[    0.916155] usbcore: registered new interface driver usbfs
[    0.923901] usbcore: registered new interface driver hub
[    0.930102] usbcore: registered new device driver usb
[    0.963853] clocksource: Switched to clocksource riscv_clocksource
[    1.015821] NET: Registered protocol family 2
[    1.038850] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    1.048465] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    1.059207] TCP bind hash table entries: 8192 (order: 5, 131072 bytes, linear)
[    1.071891] TCP: Hash tables configured (established 8192 bind 8192)
[    1.086040] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.093739] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.105640] NET: Registered protocol family 1
[    1.136744] RPC: Registered named UNIX socket transport module.
[    1.142113] RPC: Registered udp transport module.
[    1.147880] RPC: Registered tcp transport module.
[    1.151934] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   13.632637] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[   13.970240] NFS: Registering the id_resolver key type
[   13.976013] Key type id_resolver registered
[   13.979499] Key type id_legacy registered
[   13.988421] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[   16.276119] io scheduler mq-deadline registered
[   16.280065] io scheduler kyber registered
[   18.214104] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[   18.267900] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[   18.807426] printk: console [ttyS0] enabled
[   18.807426] printk: console [ttyS0] enabled
[   18.855178] xilinx_spi 20000000.xps-spi: at [mem 0x20000000-0x20000fff], irq=10
[   18.855178] xilinx_spi 20000000.xps-spi: at [mem 0x20000000-0x20000fff], irq=10
[   18.889284] libphy: Fixed MDIO Bus: probed
[   18.889284] libphy: Fixed MDIO Bus: probed
[   18.920039] lowrisc-digilent-ethernet: Lowrisc ethernet platform (30000000-30007FFF) mapped to ffffffd004028000
[   18.920039] lowrisc-digilent-ethernet: Lowrisc ethernet platform (30000000-30007FFF) mapped to ffffffd004028000
[   19.007009] libphy: GPIO Bitbanged LowRISC: probed
[   19.007009] libphy: GPIO Bitbanged LowRISC: probed
[   19.014990] Probing lowrisc-0:01 (address 1)
[   19.014990] Probing lowrisc-0:01 (address 1)
[   19.048077] RTL8211E Gigabit Ethernet lowrisc-0:01: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=lowrisc-0:01, irq=POLL)
[   19.048077] RTL8211E Gigabit Ethernet lowrisc-0:01: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=lowrisc-0:01, irq=POLL)
[   19.086690] lowrisc-eth 30000000.lowrisc-eth: Lowrisc Ether100MHz registered
[   19.086690] lowrisc-eth 30000000.lowrisc-eth: Lowrisc Ether100MHz registered
[   19.102002] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   19.102002] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   19.165939] mmc_spi spi0.0: SD/MMC host mmc0, no WP, no poweroff, cd polling
[   19.165939] mmc_spi spi0.0: SD/MMC host mmc0, no WP, no poweroff, cd polling
[   19.186260] usbcore: registered new interface driver usbhid
[   19.186260] usbcore: registered new interface driver usbhid
[   19.195295] usbhid: USB HID core driver
[   19.195295] usbhid: USB HID core driver
[   19.235453] NET: Registered protocol family 10
[   19.235453] NET: Registered protocol family 10
[   19.292572] Segment Routing with IPv6
[   19.292572] Segment Routing with IPv6
[   19.301215] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   19.301215] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   19.331683] NET: Registered protocol family 17
[   19.331683] NET: Registered protocol family 17
[   19.357165] Key type dns_resolver registered
[   19.357165] Key type dns_resolver registered
[   19.405513] Freeing unused kernel memory: 184K
[   19.405513] Freeing unused kernel memory: 184K
[   19.434596] Run /init as init process
[   19.434596] Run /init as init process
[   19.453833] mmc0: host does not support reading read-only switch, assuming write-enable
[   19.453833] mmc0: host does not support reading read-only switch, assuming write-enable
[   19.466468] mmc0: new SDHC card on SPI
[   19.466468] mmc0: new SDHC card on SPI
[   19.547475] mmcblk0: mmc0:0000 SD16G 14.5 GiB 
[   19.547475] mmcblk0: mmc0:0000 SD16G 14.5 GiB 
[   20.177821]  mmcblk0: p1 p2
[   20.177821]  mmcblk0: p1 p2
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
Saving random seed: [   25.629738] random: dd: uninitialized urandom read (512 bytes read)
[   25.629738] random: dd: uninitialized urandom read (512 bytes read)
OK
Starting rpcbind: OK
[   27.084800] Open device, request interrupt 11
[   27.084800] Open device, request interrupt 11
[   31.694763] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   31.694763] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   33.415042] random: crng init done
[   33.415042] random: crng init done
Starting sshd: OK
NFS preparation skipped, OK
# ls
README.md      init           mnt            sbin           var
bin            lib            opt            sys
cachetest.elf  lib64          proc           tetris
dev            linuxrc        root           tmp
etc            media          run            usr
#

**Comment by Gchauvon** [comment] 2024-07-12 08:25
This issue is a duplicate of https://github.com/openhwgroup/cva6-sdk/issues/99. I believe it is a linux/software issue so CVA6 repository is not the right place for it.

@JeanRochCoulon I think we can close this issue.

**Comment by JeanRochCoulon** [comment] 2024-07-12 08:45
Thanks @Gchauvon

**Closed by JeanRochCoulon** 2024-07-12 08:45 UTC
Labels: notCV32A65X
