### ISSUE TITLE
../configure: No such file or directory

### ISSUE THREAD

**Issue by Rayz-b** [openhwgroup/cva6#812] opened 2022-02-04 09:59 UTC
error while running following code from [README.md](https://github.com/openhwgroup/cva6#running-user-space-applications):
<code>mkdir build</code>
<code>cd build</code>
<code>../configure --prefix=$RISCV --host=riscv64-unknown-elf</code>
ERROR:
<code>../configure: No such file or directory</code>
the <code>configure</code> file seems to be missing from root directory of the project

**Comment by pcotret** [comment] 2022-02-17 22:15
These commands are basically done in this script: https://github.com/openhwgroup/cva6/blob/master/ci/install-riscvpk.sh
It will `cd` in the `riscv-pk`repository. The `configure`file is available there: https://github.com/riscv-software-src/riscv-pk/blob/master/configure

**Comment by MikeOpenHWGroup** [comment] 2023-02-17 02:40
Thanks for your help with this @pcotret.

Hi @Rayz-b.  This Issue was responded to a year ago so I am going to assume that the problem is resolved and will Close the Issue.  Please feel free to re-open it (or create a new one) if you are still having problems.

**Closed by MikeOpenHWGroup** 2023-02-17 02:40 UTC
Labels: Component:Tool-and-build, Type:Question, Status:Invalid

**Comment by hhhsiang** [comment] 2023-03-01 12:52
hi @pcotret , so we don't need to execute the following commands, right?
`mkdir build`
`cd build`
`../configure --prefix=$RISCV --host=riscv64-unknown-elf`
`make`
`make install`
They have been done in this script: https://github.com/openhwgroup/cva6/blob/master/ci/install-riscvpk.sh
Thank you very much!
